
import React, { createContext, useContext, useState, ReactNode } from "react";

// Define the available languages
type Language = "pt" | "en";

// Define the translations interface
interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  pt: {
    inicio: "Início",
    projetos: "Projetos",
    projetosDesc: "Transformando vidas através da arte e cultura",
    sobre: "Sobre",
    noticias: "Notícias",
    edicoes: "Edições",
    eventos: "Eventos",
    revistas: "Revistas",
    contato: "Contato",
    galeria: "Galeria",
    envieMensagem: "Envie uma mensagem",
    enviarMensagem: "Enviar Mensagem",
    nossaMissao: "Nossa Missão",
    missaoDesc:
      "Promover a arte e a cultura como ferramentas de transformação social, incentivando a diversidade, a inclusão e o desenvolvimento das comunidades através de projetos inovadores e acessíveis.",
    ultimasNoticias: "Últimas Notícias",
    emBreve: "Em breve",
    faleConosco: "Fale Conosco",
    linksRapidos: "Links Rápidos",
    transformandoVidas: "Transformando vidas através da arte e cultura",
    cnpj: "CNPJ",
    direitosReservados: "Todos os direitos reservados.",
    lerMais: "Ler mais",
    saibaMais: "Saiba mais",
    saibaMais20Anos: "Saiba mais sobre os 20 anos",
    trocarIdioma: "Trocar idioma",
    diminuirFonte: "Diminuir tamanho da fonte",
    aumentarFonte: "Aumentar tamanho da fonte",
    conhecaNossosProjetos: "Conheça Nossos Projetos",
    sobreNos: "Sobre Nós",
    quemSomos: "Quem Somos",
    missaoVisaoValores: "Missão, Visão e Valores",
    ondeAtuamos: "Onde Atuamos",
    reconhecimentos: "Reconhecimentos",
    nossaHistoria: "Nossa História",
    conecteConosco: "Conecte-se Conosco",
    seguirInstagram: "Seguir no Instagram",
    seguirFacebook: "Seguir no Facebook",
    premioPlumas: "Prêmio Plumas & Paetês",
    premioDesc: "Reconhecendo os artífices do carnaval carioca",
    categoriasPremio: "Categorias do Prêmio",
    vencedoresAnteriores: "Vencedores Anteriores",
    inscricoes: "Inscrições",
    timelineEdicoes: "Timeline das Edições",
    proximosEventos: "Próximos Eventos",
    eventosPassados: "Eventos Passados",
    calendario: "Calendário",
    fotosEventos: "Fotos dos Eventos",
    oficinas: "Oficinas e Capacitações",
    revistaDigital: "Revista Digital",
    ultimaEdicao: "Última Edição",
    todasEdicoes: "Todas as Edições",
    assinar: "Assinar",
    galeriaFotos: "Galeria de Fotos",
    filtrarPor: "Filtrar por",
    ano: "Ano",
    tipoEvento: "Tipo de Evento",
    nome: "Nome",
    email: "Email",
    telefone: "Telefone",
    mensagem: "Mensagem",
    endereco: "Endereço",
    redesSociais: "Redes Sociais",
    sigaNosInstagram: "Siga-nos no Instagram",
    equipe: "Nossa Equipe",
    fundador: "Fundador e Diretor",
    produtor: "Produtor Cultural",
    estilista: "Estilista",
    criadorPremio: "Criador do Prêmio Plumas & Paetês",
    seguidores: "seguidores",
    publicacoes: "publicações",
    parceirosEstrategicos: "Parceiros Estratégicos",
    edicao: "edição",
    revista: "Revista",
    lerOnline: "Ler Online",
    baixarPDF: "Baixar PDF",
    arquivoRevistas: "Arquivo de Revistas",
    todas: "Todas",
    paginas: "páginas",
    ler: "Ler",
    producaoEventos: "Produção de Eventos",
    nossosServicos: "Nossos Serviços",
    portfolio: "Portfólio",
    entrarContato: "Entrar em Contato",
    blog: "Blog & Notícias",
    carnaval2025: "Carnaval 2025",
    descricaoCarnaval: "Grande desfile e celebração da cultura popular",
    festivalCultural: "Festival Cultural",
    descricaoFestival: "Semana de arte, cultura e economia criativa",
    heroSubtitulo: "Transformando a sociedade brasileira por meio da economia criativa",
    quemSomosTexto1: "Criado em 2005 com o intuito de reconhecer e valorizar os artistas anônimos do carnaval carioca, amplificando as suas vozes e intermediando a ascensão de suas carreiras profissionais, o Instituto Plumas & Paetês Cultural logo se tornou muito maior do que a premiação carnavalesca que lhe deu origem.",
    quemSomosTexto2: "Mantendo a sua premissa inicial, de iluminar os bastidores da economia criativa, estimulando a renda de seus fazedores e democratizando o acesso à arte por eles produzida, o Plumas & Paetês percebeu que podia mais e decidiu ampliar o seu alcance, produzindo uma série de eventos e projetos culturais em diversas regiões do país.",
    projetosProdutosEventos: "Projetos, Produtos e Eventos",
    projetosProdutosEventosDesc: "Conheça as principais iniciativas desenvolvidas pelo Instituto ao longo de duas décadas de atuação",
    ctaTitle: "Faça Parte da Transformação Cultural",
    ctaSubtitle: "Junte-se a nós na missão de valorizar a cultura brasileira",
    project1Title: "Prêmio Plumas & Paetês Cultural",
    project1Desc: "Criado em 2005, celebra os profissionais que atuam nos bastidores da produção, criação e cobertura dos desfiles das escolas de samba do Rio de Janeiro. Mais de 1000 troféus distribuídos a mais de 1400 premiados em 51 categorias profissionais.",
    project2Title: "Oficinas de Capacitação e Gestão Artísticas",
    project2Desc: "Desde 2008 o Instituto ministra oficinas de formação e gestão artística, com atuação nas cidades do Rio de Janeiro e Brasília.",
    project3Title: "Revista Plumas e Paetês Cultural",
    project3Desc: "Publicação anual lançada em 2010 que exalta os artistas e a história do carnaval carioca. De circulação gratuita, com tiragem anual de 5000 exemplares.",
    project4Title: "Produção de Espetáculos Musicais",
    project4Desc: "A partir de 2012, produz espetáculos teatrais/musicais retratando a vida e obra de homenageados como Elza Soares, Chiquinha Gonzaga, Rainhas do Rádio e Donga.",
    project5Title: "Coroa do Rei Momo",
    project5Desc: "Desde 2014 é responsável pela confecção da coroa do Rei Momo e curadoria dos acessórios temáticos da corte nas cidades do Rio de Janeiro, Niterói, Maricá e Cruz Alta (RS).",
    project6Title: "Júri de Carnaval",
    project6Desc: "Desde 2015 coordena o corpo de jurados dos desfiles das escolas de samba dos grupos Especial e Acesso de Vitória (ES), e das séries A, B, C e D do Rio de Janeiro.",
    project7Title: "Busto do Mestre Monarco",
    project7Desc: "Em 2016, instalou o busto do compositor Monarco na quadra da Portela, um trabalho do artista Vinicius Vaitsmann.",
    project8Title: "Livro '90 Anos de Braços Abertos para os Grandes Eventos'",
    project8Desc: "Publicação de 2021 que celebrou os 90 anos da estátua do Cristo Redentor, tendo o Instituto como proponente do projeto.",
    project9Title: "Projetos de Lei",
    project9Desc: "Atuou junto ao deputado estadual Noel de Carvalho e ao vereador Marcio Ribeiro para elaboração das leis 9.950/2023 (estadual) e 8167/2023 (municipal), estabelecendo o dia 28 de setembro como o dia do Profissional da Economia Criativa de Carnaval.",
    quemSomosTexto3: "Incansável em sua missão de transformar a sociedade brasileira por meio da cultura, o Instituto desenvolveu, ao longo das duas últimas décadas, uma série de ações, dentre as quais se destacam a coordenação de eventos artísticos e de promoção da diversidade cultural (realizados no Museu do Amanhã, no Hotel Vila Galé, na Cidade do Samba, etc.), a elaboração de livro e revistas, o desenvolvimento de Oficinas de Capacitação e Gestão Artística, a Produção de espetáculos teatrais/musicais, a Coordenação de corpo de jurados dos desfiles das escolas de samba do Rio de Janeiro (RJ) e Vitória (ES), a confecção da coroa de Rei Momo e demais acessórios da Corte Momesca das cidades do Rio de Janeiro, Niterói, Maricá e Cruz Alta (RS) e a atuação na elaboração de projetos de lei voltados à economia criativa.",
    quemSomosTexto4: "Empreendido por um experiente e diverso grupo de produtores, o Plumas & Paetês Cultural se tornou uma das mais importantes referências do seu segmento, sendo chancelado, desde 2012, pela Organização dos Estados Ibero-americanos – (OEI) e outorgado, em 2015, pela Comissão de Cultura da ALERJ, com o Diploma Heloneida Studart, em virtude do seu destaque na promoção da cultura no estado.",
    nossosPilares: "Nossos Pilares",
    nossosPilaresDesc: "Transformando vidas através da cultura e do carnaval",
    missaoTitle: "Missão",
    missaoCardDesc: "Transformar a sociedade brasileira por meio da economia criativa.",
    missaoCardExpanded: "Iluminamos os bastidores da economia criativa, estimulando a renda de seus fazedores e democratizando o acesso à arte por eles produzida.",
    visaoCardTitle: "Visão",
    visaoCardDesc: "Ser um agente amplificador da riqueza cultural do país, iluminando a arte de seus fazedores e promovendo a democratização do seu acesso.",
    visaoCardExpanded: "Expandimos constantemente nossa atuação, desenvolvendo eventos e projetos culturais em diversas regiões do país.",
    valoresCardTitle: "Valores",
    valoresCardDesc: "Criatividade, diversidade, acessibilidade e sustentabilidade.",
    valoresCardExpanded: "Incansáveis em nossa missão de transformar a sociedade brasileira por meio da cultura e economia criativa.",
    verMenos: "Ver Menos",
    followEventsCaption: "Acompanhe nossos eventos e ações culturais!",
    privacyPolicy: "Política de Privacidade",
    termsOfUse: "Termos de Uso",
    nenhumaFotoEncontrada: "Nenhuma foto encontrada",
    footerAbout: "Transformando a sociedade brasileira através da cultura e economia criativa, valorizando artistas e promovendo a arte popular desde 2005.",
    conhecaNossaHistoria: "Conheça Nossa História",
    videoDescricao: "Assista ao vídeo e descubra mais sobre nossa trajetória de 20 anos transformando vidas através da cultura",
  },
  en: {
    inicio: "Home",
    projetos: "Projects",
    projetosDesc: "Transforming lives through art and culture",
    sobre: "About",
    noticias: "News",
    edicoes: "Editions",
    eventos: "Events",
    revistas: "Magazines",
    contato: "Contact",
    galeria: "Gallery",
    envieMensagem: "Send a message",
    enviarMensagem: "Send Message",
    nossaMissao: "Our Mission",
    missaoDesc:
      "Promote art and culture as tools for social transformation, encouraging diversity, inclusion, and community development through innovative and accessible projects.",
    ultimasNoticias: "Latest News",
    emBreve: "Coming soon",
    faleConosco: "Contact Us",
    linksRapidos: "Quick Links",
    transformandoVidas: "Transforming lives through art and culture",
    cnpj: "CNPJ",
    direitosReservados: "All rights reserved.",
    lerMais: "Read more",
    saibaMais: "Learn more",
    saibaMais20Anos: "Learn more about the 20 years",
    trocarIdioma: "Switch language",
    diminuirFonte: "Decrease font size",
    aumentarFonte: "Increase font size",
    conhecaNossosProjetos: "Discover Our Projects",
    sobreNos: "About Us",
    quemSomos: "Who We Are",
    missaoVisaoValores: "Mission, Vision and Values",
    ondeAtuamos: "Where We Operate",
    reconhecimentos: "Recognitions",
    nossaHistoria: "Our History",
    conecteConosco: "Connect With Us",
    seguirInstagram: "Follow on Instagram",
    seguirFacebook: "Follow on Facebook",
    premioPlumas: "Plumas & Paetês Award",
    premioDesc: "Recognizing the artisans of Rio's carnival",
    categoriasPremio: "Award Categories",
    vencedoresAnteriores: "Previous Winners",
    inscricoes: "Registration",
    timelineEdicoes: "Edition Timeline",
    proximosEventos: "Upcoming Events",
    eventosPassados: "Past Events",
    calendario: "Calendar",
    fotosEventos: "Event Photos",
    oficinas: "Workshops & Training",
    revistaDigital: "Digital Magazine",
    ultimaEdicao: "Latest Edition",
    todasEdicoes: "All Editions",
    assinar: "Subscribe",
    galeriaFotos: "Photo Gallery",
    filtrarPor: "Filter by",
    ano: "Year",
    tipoEvento: "Event Type",
    nome: "Name",
    email: "Email",
    telefone: "Phone",
    mensagem: "Message",
    endereco: "Address",
    redesSociais: "Social Media",
    sigaNosInstagram: "Follow us on Instagram",
    equipe: "Our Team",
    fundador: "Founder and Director",
    produtor: "Cultural Producer",
    estilista: "Stylist",
    criadorPremio: "Creator of Prêmio Plumas & Paetês",
    seguidores: "followers",
    publicacoes: "posts",
    parceirosEstrategicos: "Strategic Partners",
    edicao: "edition",
    revista: "Magazine",
    lerOnline: "Read Online",
    baixarPDF: "Download PDF",
    arquivoRevistas: "Magazine Archive",
    todas: "All",
    paginas: "pages",
    ler: "Read",
    producaoEventos: "Event Production",
    nossosServicos: "Our Services",
    portfolio: "Portfolio",
    entrarContato: "Get in Touch",
    blog: "Blog & News",
    carnaval2025: "Carnival 2025",
    descricaoCarnaval: "Grand parade and celebration of popular culture",
    festivalCultural: "Cultural Festival",
    descricaoFestival: "Week of art, culture and creative economy",
    heroSubtitulo: "Transforming Brazilian society through the creative economy",
    quemSomosTexto1: "Created in 2005 with the aim of recognizing and valuing the anonymous artists of Rio's carnival, amplifying their voices and facilitating their professional advancement, the Instituto Plumas & Paetês Cultural soon became much more than the carnival award that gave it origin.",
    quemSomosTexto2: "Maintaining its initial premise of illuminating the backstage of the creative economy, stimulating the income of its creators and democratizing access to the art they produce, Plumas & Paetês realized it could do more and decided to expand its reach, producing a series of cultural events and projects in various regions of the country.",
    projetosProdutosEventos: "Projects, Products and Events", 
    projetosProdutosEventosDesc: "Discover the main initiatives developed by the Institute over two decades of activity",
    ctaTitle: "Join the Cultural Transformation",
    ctaSubtitle: "Join us in the mission of valuing Brazilian culture",
    project1Title: "Plumas & Paetês Cultural Award",
    project1Desc: "Created in 2005, it celebrates the professionals working behind the scenes of the production, creation, and coverage of Rio de Janeiro's samba school parades. Over 1,000 trophies awarded to more than 1,400 winners across 51 professional categories.",
    project2Title: "Artistic Training and Management Workshops",
    project2Desc: "Since 2008, the Institute has offered training and artistic management workshops in the cities of Rio de Janeiro and Brasília.",
    project3Title: "Plumas & Paetês Cultural Magazine",
    project3Desc: "Annual publication launched in 2010 that highlights the artists and history of Rio's carnival. Free circulation with an annual print run of 5,000 copies.",
    project4Title: "Production of Musical Shows",
    project4Desc: "Since 2012, produces theatrical/musical shows portraying the life and work of honorees such as Elza Soares, Chiquinha Gonzaga, Rainhas do Rádio, and Donga.",
    project5Title: "King Momo's Crown",
    project5Desc: "Since 2014, responsible for crafting King Momo's crown and curating the themed accessories of the court in the cities of Rio de Janeiro, Niterói, Maricá, and Cruz Alta (RS).",
    project6Title: "Carnival Jury",
    project6Desc: "Since 2015, coordinates the jury for the samba school parades of the Special and Access groups in Vitória (ES), and the A, B, C, and D series in Rio de Janeiro.",
    project7Title: "Bust of Mestre Monarco",
    project7Desc: "In 2016, installed the bust of composer Monarco at Portela's court, a work by artist Vinicius Vaitsmann.",
    project8Title: "Book '90 Years with Open Arms for the Great Events'",
    project8Desc: "A 2021 publication celebrating the 90th anniversary of the Christ the Redeemer statue, with the Institute as the project's proponent.",
    project9Title: "Bills",
    project9Desc: "Worked alongside state deputy Noel de Carvalho and councilman Marcio Ribeiro on drafting laws 9.950/2023 (state) and 8167/2023 (municipal), establishing September 28 as the Day of the Creative Economy Carnival Professional.",
    quemSomosTexto3: "Tireless in its mission to transform Brazilian society through culture, the Institute has developed, over the past two decades, a series of actions, among which stand out the coordination of artistic events and promotion of cultural diversity (held at the Museum of Tomorrow, Hotel Vila Galé, Cidade do Samba, etc.), the production of books and magazines, the development of Training and Artistic Management Workshops, the Production of theatrical/musical shows, the Coordination of jury bodies for the samba school parades in Rio de Janeiro (RJ) and Vitória (ES), the crafting of King Momo's crown and other accessories for the Momesca Court in the cities of Rio de Janeiro, Niterói, Maricá, and Cruz Alta (RS), and the work on drafting bills aimed at the creative economy.",
    quemSomosTexto4: "Undertaken by an experienced and diverse group of producers, Plumas & Paetês Cultural has become one of the most important references in its segment, being endorsed since 2012 by the Organization of Ibero-American States – (OEI) and awarded in 2015 by the ALERJ Culture Commission with the Heloneida Studart Diploma, due to its excellence in promoting culture in the state.",
    nossosPilares: "Our Pillars",
    nossosPilaresDesc: "Transforming lives through culture and carnival",
    missaoTitle: "Mission",
    missaoCardDesc: "Transform Brazilian society through the creative economy.",
    missaoCardExpanded: "We illuminate the backstage of the creative economy, stimulating the income of its makers and democratizing access to the art they produce.",
    visaoCardTitle: "Vision",
    visaoCardDesc: "To be an amplifying agent of the country's cultural richness, illuminating the art of its makers and promoting democratization of access.",
    visaoCardExpanded: "We constantly expand our activities, developing cultural events and projects in various regions of the country.",
    valoresCardTitle: "Values",
    valoresCardDesc: "Creativity, diversity, accessibility and sustainability.",
    valoresCardExpanded: "Tireless in our mission to transform Brazilian society through culture and creative economy.",
    verMenos: "See Less",
    followEventsCaption: "Follow our events and cultural actions!",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    nenhumaFotoEncontrada: "No photos found",
    footerAbout: "Transforming Brazilian society through culture and creative economy, valuing artists and promoting popular art since 2005.",
    conhecaNossaHistoria: "Discover Our Story",
    videoDescricao: "Watch the video and discover more about our 20-year journey transforming lives through culture",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translate: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>("pt");

  const translate = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};
